title: Xinyue Zhao's Homepage
page-top-title: Xinyue Zhao
top-section-bg-text: Communication Engineering
home-subtitle: Xinyue Zhao | 赵欣悦
copyright-text: '&copy; Xinyue Zhao 2023-2027 All Rights Reserved.'

url: "https://xz528851-hub.github.io"
baseurl: ""